#!/usr/bin/sh

# This stript downloads and parses these files:
# http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt
# http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt
# in order to generate tables of zero-width, and double-width characters.

# Files listed above belong to Unicode. You can find the license here:
# http://www.unicode.org/copyright.html
# or here:
# http://www.unicode.org/terms_of_use.html

# To generate new 'widechars.h':
# $ ./gen-widechars.sh > src/include/widechars.h

eaw=$(curl -s http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt)
udb=$(curl -s http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt)

echo "/*"
echo " * This file was generated by a script using these files:"
echo " * http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt"
echo " * http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt"
echo " * These files belong to Unicode. You can find the license here:"
echo " * http://www.unicode.org/copyright.html"
echo " * or here:"
echo " * http://www.unicode.org/terms_of_use.html"
echo " */"
echo
echo "#ifndef WIDECHARS_H"
echo "#define WIDECHARS_H"
echo
echo "// A sorted list of ranges of Unicode codepoints of double-width characters"
echo "static const unsigned int double_width[][2] = {"
while IFS='' read -r line || [ -n "$line" ]; do
	if [ "${line:0:1}" == "#" ]; then
		continue
	fi
	range=$(echo $line | cut -d ';' -f 1)
	a=$((16#$(echo $range | cut -d '.' -f 1)))
	b=$((16#$(echo $range | cut -d '.' -f 3)))
	category=$(echo $line | cut -d ';' -f 2 | cut -d ' ' -f 1)
	if [ "$category" == "F" ] || [ "$category" == "W" ]; then
		printf "\t{0x%06x, 0x%06x},\n" $a $b
	fi
done <<< "$eaw"
echo "};"
echo
echo "// A sorted list of ranges of Unicode codepoints of zero-width characters"
echo "static const unsigned int zero_width[][2] = {"
ra=0
rb=0
while IFS='' read -r line || [[ -n "$line" ]]; do
	cp=$((16#$(echo $line | cut -d ';' -f 1)))
	name=$(echo $line | cut -d ';' -f 2)
	category=$(echo $line | cut -d ';' -f 3)
	if [ "${name:0:16}" == "HANGUL JUNGSEONG" ] \
		|| [ "${name:0:16}" == "HANGUL JONGSEONG" ] \
		|| [ "$category" == "Cf" ] \
		|| [ "$category" == "Mn" ] \
		|| [ "$category" == "Me" ]; then
		if (( cp == rb+1 )); then
			rb=$cp
			continue
		else
			printf "\t{0x%06x, 0x%06x},\n" $ra $rb
			ra=$cp
			rb=$cp
		fi
	fi
done <<< "$udb"
echo "};"
echo
echo "#endif"
